# Conda recipe example.
package:
    name: pyugrid
    version: "0.1.5"

source:
    fn: pyugrid-0.1.5.tar.gz
    url: https://pypi.python.org/packages/source/p/pyugrid/pyugrid-0.1.5.tar.gz
    md5: d8d69f117a6ef4179bdd5a2cc1eb1b6c

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4
        - scipy

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    license: BSD
    summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions'
